"""phase 11 opportunity scoring

Revision ID: 15fad83a40af
Revises: ed0f710913e6
Create Date: 2026-08-20 07:27:49.151834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15fad83a40af'
down_revision: Union[str, Sequence[str], None] = 'ed0f710913e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.Uuid(), nullable=False),
    sa.Column('reference_domain_id', sa.Uuid(), nullable=True),
    sa.Column('composite_score', sa.Integer(), nullable=True),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['reference_domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'reference_domain_id', name='uq_opportunity_score_pair')
    )
    op.create_index(op.f('ix_opportunity_scores_domain_id'), 'opportunity_scores', ['domain_id'], unique=False)
    op.create_index(op.f('ix_opportunity_scores_reference_domain_id'), 'opportunity_scores', ['reference_domain_id'], unique=False)
    # NOTE: autogenerate wanted to drop 'ix_pages_fulltext' here because
    # it's a raw functional GIN index (created via op.execute in the
    # phase-10 migration) that isn't expressible in SQLAlchemy's ORM
    # metadata, so the diff tool sees it as "not declared" and proposes
    # removing it. It's real, intentional, and stays. See docs/DATABASE.md.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_scores_reference_domain_id'), table_name='opportunity_scores')
    op.drop_index(op.f('ix_opportunity_scores_domain_id'), table_name='opportunity_scores')
    op.drop_table('opportunity_scores')
    # ### end Alembic commands ###
