"""phase 2 structured metadata and contact candidates

Revision ID: 3584c59f5ad9
Revises: b4041241745f
Create Date: 2026-08-18 09:50:59.414611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3584c59f5ad9'
down_revision: Union[str, Sequence[str], None] = 'b4041241745f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('schema_org', sa.JSON(), nullable=True))
    op.add_column('pages', sa.Column('open_graph', sa.JSON(), nullable=True))
    op.add_column('pages', sa.Column('twitter_card', sa.JSON(), nullable=True))
    op.add_column('pages', sa.Column('images', sa.JSON(), nullable=True))
    op.add_column('pages', sa.Column('pdf_links', sa.JSON(), nullable=True))
    op.add_column('pages', sa.Column('social_links', sa.JSON(), nullable=True))
    op.add_column('pages', sa.Column('embeds', sa.JSON(), nullable=True))
    op.add_column('pages', sa.Column('contact_emails', sa.JSON(), nullable=True))
    op.add_column('pages', sa.Column('contact_phones', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'contact_phones')
    op.drop_column('pages', 'contact_emails')
    op.drop_column('pages', 'embeds')
    op.drop_column('pages', 'social_links')
    op.drop_column('pages', 'pdf_links')
    op.drop_column('pages', 'images')
    op.drop_column('pages', 'twitter_card')
    op.drop_column('pages', 'open_graph')
    op.drop_column('pages', 'schema_org')
    # ### end Alembic commands ###
