"""phase 5 competitor intelligence and link gap

Revision ID: 4b11f62baa91
Revises: 4d4f7236ee73
Create Date: 2026-08-20 06:49:03.467571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b11f62baa91'
down_revision: Union[str, Sequence[str], None] = '4d4f7236ee73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('primary_domain_id', sa.Uuid(), nullable=False),
    sa.Column('competitor_domain_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['primary_domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('primary_domain_id', 'competitor_domain_id', name='uq_competitor_pair')
    )
    op.create_index(op.f('ix_competitor_relationships_competitor_domain_id'), 'competitor_relationships', ['competitor_domain_id'], unique=False)
    op.create_index(op.f('ix_competitor_relationships_primary_domain_id'), 'competitor_relationships', ['primary_domain_id'], unique=False)
    op.create_table('link_gap_opportunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('primary_domain_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_domain_id', sa.Uuid(), nullable=False),
    sa.Column('competitor_overlap_count', sa.Integer(), nullable=False),
    sa.Column('competitor_domain_ids', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='link_gap_confidence'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['primary_domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('primary_domain_id', 'candidate_domain_id', name='uq_link_gap_pair')
    )
    op.create_index(op.f('ix_link_gap_opportunities_candidate_domain_id'), 'link_gap_opportunities', ['candidate_domain_id'], unique=False)
    op.create_index(op.f('ix_link_gap_opportunities_primary_domain_id'), 'link_gap_opportunities', ['primary_domain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_gap_opportunities_primary_domain_id'), table_name='link_gap_opportunities')
    op.drop_index(op.f('ix_link_gap_opportunities_candidate_domain_id'), table_name='link_gap_opportunities')
    op.drop_table('link_gap_opportunities')
    op.drop_index(op.f('ix_competitor_relationships_primary_domain_id'), table_name='competitor_relationships')
    op.drop_index(op.f('ix_competitor_relationships_competitor_domain_id'), table_name='competitor_relationships')
    op.drop_table('competitor_relationships')
    # ### end Alembic commands ###
