"""phase 3 backlink engine

Revision ID: 4d4f7236ee73
Revises: 3584c59f5ad9
Create Date: 2026-08-18 12:53:05.290231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PGEnum


# revision identifiers, used by Alembic.
revision: str = '4d4f7236ee73'
down_revision: Union[str, Sequence[str], None] = '3584c59f5ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backlink_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('target_domain_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('DIRECT_CRAWL', 'COMMON_CRAWL', 'SEARCH_DISCOVERED', 'USER_PROVIDED', name='backlink_source_type'), nullable=False),
    sa.Column('discovery_method', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='backlink_candidate_status'), nullable=False),
    sa.Column('rejection_reason', sa.Enum('SOURCE_UNREACHABLE', 'TARGET_NOT_FOUND', 'BLOCKED', name='backlink_rejection_reason'), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backlink_candidates_target_domain_id'), 'backlink_candidates', ['target_domain_id'], unique=False)
    op.create_table('backlink_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('source_domain_id', sa.Uuid(), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('target_domain_id', sa.Uuid(), nullable=False),
    sa.Column('anchor_text', sa.Text(), nullable=True),
    sa.Column('surrounding_text', sa.Text(), nullable=True),
    sa.Column('rel_nofollow', sa.Boolean(), nullable=False),
    sa.Column('rel_sponsored', sa.Boolean(), nullable=False),
    sa.Column('rel_ugc', sa.Boolean(), nullable=False),
    # create_type=False: the "link_position" PG enum type already exists
    # (created for page_links in the phase-1 migration) -- this column
    # reuses it, it must not try to CREATE TYPE again. (Using the
    # dialect-specific postgresql.ENUM here because the generic sa.Enum's
    # create_type kwarg does not reliably suppress the CREATE TYPE DDL
    # event in this SQLAlchemy version.)
    sa.Column('link_position', PGEnum('NAV', 'FOOTER', 'BODY', 'SIDEBAR', 'UNKNOWN', name='link_position', create_type=False), nullable=False),
    sa.Column('link_type', sa.Enum('NAVIGATION', 'FOOTER', 'SPONSORED', 'UGC', 'UNKNOWN', name='backlink_link_type'), nullable=False),
    sa.Column('source_canonical_url', sa.String(length=2048), nullable=True),
    sa.Column('source_http_status', sa.Integer(), nullable=True),
    sa.Column('source_is_indexable', sa.Boolean(), nullable=False),
    # create_type=False: 'backlink_source_type' is already created by the
    # backlink_candidates table above, in this same migration.
    sa.Column('source_type', PGEnum('DIRECT_CRAWL', 'COMMON_CRAWL', 'SEARCH_DISCOVERED', 'USER_PROVIDED', name='backlink_source_type', create_type=False), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('crawl_request_id', sa.Uuid(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['backlink_candidates.id'], ),
    sa.ForeignKeyConstraint(['crawl_request_id'], ['crawl_requests.id'], ),
    sa.ForeignKeyConstraint(['source_domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['target_domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backlink_observations_candidate_id'), 'backlink_observations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_backlink_observations_source_domain_id'), 'backlink_observations', ['source_domain_id'], unique=False)
    op.create_index(op.f('ix_backlink_observations_target_domain_id'), 'backlink_observations', ['target_domain_id'], unique=False)
    op.create_table('backlinks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_domain_id', sa.Uuid(), nullable=False),
    sa.Column('target_domain_id', sa.Uuid(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('latest_observation_id', sa.Uuid(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['latest_observation_id'], ['backlink_observations.id'], ),
    sa.ForeignKeyConstraint(['source_domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['target_domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url', 'target_url', name='uq_backlinks_source_target')
    )
    op.create_index(op.f('ix_backlinks_source_domain_id'), 'backlinks', ['source_domain_id'], unique=False)
    op.create_index(op.f('ix_backlinks_target_domain_id'), 'backlinks', ['target_domain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backlinks_target_domain_id'), table_name='backlinks')
    op.drop_index(op.f('ix_backlinks_source_domain_id'), table_name='backlinks')
    op.drop_table('backlinks')
    op.drop_index(op.f('ix_backlink_observations_target_domain_id'), table_name='backlink_observations')
    op.drop_index(op.f('ix_backlink_observations_source_domain_id'), table_name='backlink_observations')
    op.drop_index(op.f('ix_backlink_observations_candidate_id'), table_name='backlink_observations')
    op.drop_table('backlink_observations')
    op.drop_index(op.f('ix_backlink_candidates_target_domain_id'), table_name='backlink_candidates')
    op.drop_table('backlink_candidates')
    # ### end Alembic commands ###
