"""phase 12 evidence field on link gap opportunities

Revision ID: 6561114386e8
Revises: 15fad83a40af
Create Date: 2026-08-20 07:35:17.520861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6561114386e8'
down_revision: Union[str, Sequence[str], None] = '15fad83a40af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_gap_opportunities', sa.Column('evidence', sa.JSON(), nullable=False))
    # NOTE: see docs/ARCHITECTURE.md risk #16 -- ix_pages_fulltext is a
    # raw-SQL functional GIN index not expressible in ORM metadata;
    # autogenerate always proposes dropping it, and it always stays.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link_gap_opportunities', 'evidence')
    # ### end Alembic commands ###
