"""phase 18 geo observations

Revision ID: 6ed746c2b34b
Revises: 7884ad9e429f
Create Date: 2026-08-20 08:21:09.974397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed746c2b34b'
down_revision: Union[str, Sequence[str], None] = '7884ad9e429f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('engine', sa.String(length=255), nullable=False),
    sa.Column('target_domain_id', sa.Uuid(), nullable=False),
    sa.Column('observed_result', sa.Enum('CITED', 'NOT_CITED', name='geo_citation_result'), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('answer_excerpt', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_observations_target_domain_id'), 'geo_observations', ['target_domain_id'], unique=False)
    # NOTE: autogenerate proposed dropping ix_pages_fulltext here again --
    # the Phase 10 raw-SQL functional GIN index, not expressible in ORM
    # metadata. Manually stripped -- see docs/ARCHITECTURE.md risk #16.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geo_observations_target_domain_id'), table_name='geo_observations')
    op.drop_table('geo_observations')
    # ### end Alembic commands ###
