"""phase 16 backlink monitoring

Revision ID: 7884ad9e429f
Revises: 8bc9ac51bbde
Create Date: 2026-08-20 08:06:18.768484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7884ad9e429f'
down_revision: Union[str, Sequence[str], None] = '8bc9ac51bbde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backlink_monitoring_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('backlink_id', sa.Uuid(), nullable=False),
    sa.Column('change_type', sa.Enum('LOST', 'ATTRIBUTE_CHANGED', 'ANCHOR_CHANGED', 'SOURCE_STATUS_CHANGED', 'CANONICAL_CHANGED', name='backlink_change_type'), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['backlink_id'], ['backlinks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backlink_monitoring_events_backlink_id'), 'backlink_monitoring_events', ['backlink_id'], unique=False)
    op.add_column('backlinks', sa.Column('lost_at', sa.DateTime(timezone=True), nullable=True))
    # NOTE: autogenerate proposed dropping ix_pages_fulltext here again --
    # the Phase 10 raw-SQL functional GIN index, not expressible in ORM
    # metadata. Manually stripped -- see docs/ARCHITECTURE.md risk #16.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backlinks', 'lost_at')
    op.drop_index(op.f('ix_backlink_monitoring_events_backlink_id'), table_name='backlink_monitoring_events')
    op.drop_table('backlink_monitoring_events')
    # ### end Alembic commands ###
