"""phase 15 campaign funnel tracking

Revision ID: 8bc9ac51bbde
Revises: ff756d43643e
Create Date: 2026-08-20 07:58:26.302590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PGEnum


# revision identifiers, used by Alembic.
revision: str = '8bc9ac51bbde'
down_revision: Union[str, Sequence[str], None] = 'ff756d43643e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('outreach_strategy_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('current_stage', sa.Enum('SENT', 'DELIVERED', 'BOUNCED', 'OPENED', 'CLICKED', 'REPLIED', 'POSITIVE_REPLY', 'NEGATIVE_REPLY', 'UNSUBSCRIBED', 'PUBLISHED', 'BACKLINK_DETECTED', 'BACKLINK_VERIFIED', name='campaign_funnel_stage'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['outreach_strategy_id'], ['outreach_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_contact_id'), 'campaigns', ['contact_id'], unique=False)
    op.create_index(op.f('ix_campaigns_outreach_strategy_id'), 'campaigns', ['outreach_strategy_id'], unique=False)
    op.create_table('campaign_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    # create_type=False: 'campaign_funnel_stage' is already created by the
    # campaigns table above, in this same migration -- see
    # docs/ARCHITECTURE.md risk #13.
    sa.Column('stage', PGEnum('SENT', 'DELIVERED', 'BOUNCED', 'OPENED', 'CLICKED', 'REPLIED', 'POSITIVE_REPLY', 'NEGATIVE_REPLY', 'UNSUBSCRIBED', 'PUBLISHED', 'BACKLINK_DETECTED', 'BACKLINK_VERIFIED', name='campaign_funnel_stage', create_type=False), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_events_campaign_id'), 'campaign_events', ['campaign_id'], unique=False)
    # NOTE: autogenerate proposed dropping ix_pages_fulltext here again --
    # the Phase 10 raw-SQL functional GIN index, not expressible in ORM
    # metadata. Manually stripped -- see docs/ARCHITECTURE.md risk #16.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_events_campaign_id'), table_name='campaign_events')
    op.drop_table('campaign_events')
    op.drop_index(op.f('ix_campaigns_outreach_strategy_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_contact_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
