"""phase 7 prospect discovery

Revision ID: 956a582e6060
Revises: 6ed746c2b34b
Create Date: 2026-08-21 07:15:15.378644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956a582e6060'
down_revision: Union[str, Sequence[str], None] = '6ed746c2b34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.Uuid(), nullable=False),
    sa.Column('topic_query', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('RESOURCE_PAGE', 'ROUNDUP', 'GUEST_POST_BLOG', 'INDUSTRY_PUBLICATION', name='prospect_category'), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('topical_fit_score', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'topic_query', name='uq_prospect_domain_topic')
    )
    op.create_index(op.f('ix_prospects_domain_id'), 'prospects', ['domain_id'], unique=False)
    # NOTE: autogenerate proposed dropping ix_pages_fulltext here again --
    # the Phase 10 raw-SQL functional GIN index, not expressible in ORM
    # metadata. Manually stripped -- see docs/ARCHITECTURE.md risk #16.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prospects_domain_id'), table_name='prospects')
    op.drop_table('prospects')
    # ### end Alembic commands ###
