"""phase 1 crawl layer

Revision ID: b4041241745f
Revises: 
Create Date: 2026-08-18 09:06:11.750415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4041241745f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('raw_host', sa.String(length=255), nullable=False),
    sa.Column('normalized_host', sa.String(length=255), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('robots_txt_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('robots_txt_raw', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_normalized_host'), 'domains', ['normalized_host'], unique=True)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.Uuid(), nullable=False),
    sa.Column('start_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='crawl_job_status'), nullable=False),
    sa.Column('schedule', sa.Enum('ONE_TIME', 'DAILY', 'WEEKLY', 'MONTHLY', name='crawl_schedule'), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_domain_id'), 'crawl_jobs', ['domain_id'], unique=False)
    op.create_table('crawl_errors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('crawl_job_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('reason', sa.Enum('BLOCKED_ROBOTS', 'BLOCKED_CAPTCHA', 'TIMEOUT', 'DNS_FAIL', 'HTTP_4XX', 'HTTP_5XX', 'OTHER', name='crawl_error_reason'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_errors_crawl_job_id'), 'crawl_errors', ['crawl_job_id'], unique=False)
    op.create_table('crawl_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('crawl_job_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('method', sa.Enum('HTTP', 'PLAYWRIGHT', name='crawl_method'), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('redirect_chain', sa.JSON(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('html_hash', sa.String(length=64), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('structure_hash', sa.String(length=64), nullable=True),
    sa.Column('timing_ms', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_requests_crawl_job_id'), 'crawl_requests', ['crawl_job_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.Uuid(), nullable=False),
    sa.Column('crawl_request_id', sa.Uuid(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('h1', sa.JSON(), nullable=True),
    sa.Column('headings', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('robots_meta_noindex', sa.Boolean(), nullable=False),
    sa.Column('robots_meta_nofollow', sa.Boolean(), nullable=False),
    sa.Column('is_indexable', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('html_hash', sa.String(length=64), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('structure_hash', sa.String(length=64), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_request_id'], ['crawl_requests.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_domain_id'), 'pages', ['domain_id'], unique=False)
    op.create_index(op.f('ix_pages_url'), 'pages', ['url'], unique=False)
    op.create_table('page_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_page_id', sa.Uuid(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('target_domain_id', sa.Uuid(), nullable=True),
    sa.Column('anchor_text', sa.Text(), nullable=True),
    sa.Column('surrounding_text', sa.Text(), nullable=True),
    sa.Column('rel_nofollow', sa.Boolean(), nullable=False),
    sa.Column('rel_sponsored', sa.Boolean(), nullable=False),
    sa.Column('rel_ugc', sa.Boolean(), nullable=False),
    sa.Column('target_blank', sa.Boolean(), nullable=False),
    sa.Column('link_position', sa.Enum('NAV', 'FOOTER', 'BODY', 'SIDEBAR', 'UNKNOWN', name='link_position'), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['target_domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_links_source_page_id'), 'page_links', ['source_page_id'], unique=False)
    op.create_index(op.f('ix_page_links_target_domain_id'), 'page_links', ['target_domain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_links_target_domain_id'), table_name='page_links')
    op.drop_index(op.f('ix_page_links_source_page_id'), table_name='page_links')
    op.drop_table('page_links')
    op.drop_index(op.f('ix_pages_url'), table_name='pages')
    op.drop_index(op.f('ix_pages_domain_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_crawl_requests_crawl_job_id'), table_name='crawl_requests')
    op.drop_table('crawl_requests')
    op.drop_index(op.f('ix_crawl_errors_crawl_job_id'), table_name='crawl_errors')
    op.drop_table('crawl_errors')
    op.drop_index(op.f('ix_crawl_jobs_domain_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_domains_normalized_host'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
