"""phase 8 contact intelligence

Revision ID: bf0ef1b882a8
Revises: 4b11f62baa91
Create Date: 2026-08-20 07:05:30.843625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0ef1b882a8'
down_revision: Union[str, Sequence[str], None] = '4b11f62baa91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('verification_status', sa.Enum('DIRECTLY_PUBLISHED', 'VERIFIED', 'LIKELY', 'CATCH_ALL', 'ROLE_ADDRESS', 'PATTERN_INFERRED', 'UNKNOWN', 'INVALID', name='contact_verification_status'), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'email', name='uq_contacts_domain_email'),
    sa.UniqueConstraint('domain_id', 'phone', name='uq_contacts_domain_phone')
    )
    op.create_index(op.f('ix_contacts_domain_id'), 'contacts', ['domain_id'], unique=False)
    op.create_table('contact_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('page_type', sa.Enum('HOME', 'ABOUT', 'CONTACT', 'TEAM', 'AUTHOR', 'GUEST_POST', 'PRESS', 'OTHER', name='contact_page_type'), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'source_url', name='uq_contact_source')
    )
    op.create_index(op.f('ix_contact_sources_contact_id'), 'contact_sources', ['contact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_sources_contact_id'), table_name='contact_sources')
    op.drop_table('contact_sources')
    op.drop_index(op.f('ix_contacts_domain_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
