"""phase 10 guest post intelligence and page body_text

Revision ID: ed0f710913e6
Revises: eef4b88d4009
Create Date: 2026-08-20 07:21:03.584304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0f710913e6'
down_revision: Union[str, Sequence[str], None] = 'eef4b88d4009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_post_opportunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.Uuid(), nullable=False),
    sa.Column('guideline_page_url', sa.String(length=2048), nullable=True),
    sa.Column('editor_email', sa.String(length=320), nullable=True),
    sa.Column('word_count_min', sa.Integer(), nullable=True),
    sa.Column('word_count_max', sa.Integer(), nullable=True),
    sa.Column('mentions_dofollow', sa.Boolean(), nullable=False),
    sa.Column('mentions_nofollow', sa.Boolean(), nullable=False),
    sa.Column('mentions_sponsored', sa.Boolean(), nullable=False),
    sa.Column('mentions_author_bio', sa.Boolean(), nullable=False),
    sa.Column('appears_closed', sa.Boolean(), nullable=False),
    sa.Column('distinct_authors_observed', sa.Integer(), nullable=False),
    sa.Column('guest_post_probability', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_post_opportunities_domain_id'), 'guest_post_opportunities', ['domain_id'], unique=True)
    op.add_column('pages', sa.Column('body_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # docs/DATABASE.md's indexing strategy: full-text search over
    # title + meta_description + body_text, now that body_text exists.
    op.execute(
        """
        CREATE INDEX ix_pages_fulltext ON pages
        USING GIN (to_tsvector('english',
            coalesce(title, '') || ' ' || coalesce(meta_description, '') || ' ' || coalesce(body_text, '')
        ))
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_pages_fulltext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'body_text')
    op.drop_index(op.f('ix_guest_post_opportunities_domain_id'), table_name='guest_post_opportunities')
    op.drop_table('guest_post_opportunities')
    # ### end Alembic commands ###
