"""phase 9 email verification

Revision ID: eef4b88d4009
Revises: bf0ef1b882a8
Create Date: 2026-08-20 07:14:18.909461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PGEnum


# revision identifiers, used by Alembic.
revision: str = 'eef4b88d4009'
down_revision: Union[str, Sequence[str], None] = 'bf0ef1b882a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('layer_reached', sa.Enum('SYNTAX', 'DNS', 'MX', 'SMTP', name='email_verification_layer'), nullable=False),
    sa.Column('is_disposable_domain', sa.Boolean(), nullable=False),
    # create_type=False: 'contact_verification_status' already exists
    # (created for contacts.verification_status in the phase-8 migration).
    sa.Column('result_status', PGEnum('DIRECTLY_PUBLISHED', 'VERIFIED', 'LIKELY', 'CATCH_ALL', 'ROLE_ADDRESS', 'PATTERN_INFERRED', 'UNKNOWN', 'INVALID', name='contact_verification_status', create_type=False), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_contact_id'), 'email_verifications', ['contact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_verifications_contact_id'), table_name='email_verifications')
    op.drop_table('email_verifications')
    # ### end Alembic commands ###
