"""phase 14 outreach strategy

Revision ID: ff756d43643e
Revises: 6561114386e8
Create Date: 2026-08-20 07:49:37.651333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff756d43643e'
down_revision: Union[str, Sequence[str], None] = '6561114386e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_strategies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_type', sa.Enum('GUEST_POST', 'LINK_GAP', 'GENERIC', name='outreach_opportunity_type'), nullable=False),
    sa.Column('guest_post_opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('link_gap_opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('angle', sa.Text(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('recommended_content_asset', sa.Text(), nullable=True),
    sa.Column('expected_link_probability', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='outreach_difficulty'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['guest_post_opportunity_id'], ['guest_post_opportunities.id'], ),
    sa.ForeignKeyConstraint(['link_gap_opportunity_id'], ['link_gap_opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_strategies_contact_id'), 'outreach_strategies', ['contact_id'], unique=True)
    op.create_index(op.f('ix_outreach_strategies_domain_id'), 'outreach_strategies', ['domain_id'], unique=False)
    # NOTE: autogenerate proposed dropping ix_pages_fulltext here -- that's
    # the Phase 10 raw-SQL functional GIN index, not expressible in ORM
    # metadata, so the diff tool sees it as drift to correct. It isn't.
    # Manually stripped -- see docs/ARCHITECTURE.md risk #16.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_strategies_domain_id'), table_name='outreach_strategies')
    op.drop_index(op.f('ix_outreach_strategies_contact_id'), table_name='outreach_strategies')
    op.drop_table('outreach_strategies')
    # ### end Alembic commands ###
